### ISSUE TITLE
The "ENTER" key does not work as it should

### ISSUE THREAD

**Issue by playdasegunda** [patrikzudel/PatrikZeros-ChatGPT-API-UI#15]
- [ ] I have read all open and **closed** Issues and confirm that this is not a duplicate.

**Describe the bug**
"I'm not sure if it's actually a bug or intentional, but when typing a message and hitting "ENTER" instead of sending the message, it just creates a new line, like when we press (SHIFT+ENTER)."

**To Reproduce**

**Expected behavior**
I hope it works as it should, when typing a message and hitting "ENTER" it should send our request and not break to a new line. It should work like ChatGPT or any other chat bot does

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 111

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**
N/A

**Comment by patrikzudel** [comment]
Hmm definitely a bug, but I am not able to replicate this on any browser. Pressing enter should send the message and it has worked for all people I've talked to so far. 

Have you tried other browsers?

**Comment by playdasegunda** [comment]
> Hmm definitely a bug, but I am not able to replicate this on any browser. Pressing enter should send the message and it has worked for all people I've talked to so far.
> 
> Have you tried other browsers?

I found the cause of the error: the extension "Absolute Enable Right Click & Copy", installed in my Google Chrome, was activated on "localhost" and causing problems. I just disabled it on that domain, and now everything is working normally. Thanks for the help!

**Comment by patrikzudel** [comment]
Nice!
