### ISSUE TITLE
A way to change the API module would be great.

### ISSUE THREAD

**Issue by pxrunes** [patrikzudel/PatrikZeros-ChatGPT-API-UI#21]
- [x] I have read all open and **closed** Issues and confirm that this is not a duplicate.

In the settings menu, add a textbox were one can change the used modul (e.g. GPT-4, GPT3.5)

**Comment by jwwpua** [comment]
Please also allow selection of the model's token limit due to gpt4 having 8k and 32k limits depending.

**Comment by patrikzudel** [comment]
Added. It will only work if you have access to the model you want to use of course.
I don't have GPT-4 access so let me know if it works or not! (Reopen if it doesn't)

**Comment by jwwpua** [comment]
> Added. It will only work if you have access to the model you want to use of course. I don't have GPT-4 access so let me know if it works or not! (Reopen if it doesn't)

GPT-4 works! (8k version)

Thanks!
