### ISSUE TITLE
Unable to close a chat session unless another chat session exists

### ISSUE THREAD

**Issue by RahulVivekNair** [patrikzudel/PatrikZeros-ChatGPT-API-UI#24]
- [x] I have read all open and **closed** Issues and confirm that this is not a duplicate.

#### PROBLEM
The chats from the chat pane can only be closed if another chat exists. So if you have only 1 active chat in the pane, you will have to click on new chat to spawn a new chat and only then will you be able to close the old one.

#### STEPS TO REPRODUCE
1. Delete all chat sessions
2. Try to click on x to close the last remaining chat
3. Action cannot be performed
4. Click on new chat to spawn a new session
5. Now the x can be clicked on the old chat to close it

#### EXPECTED BEHAVIOUR
When you try close the last remaining chat session, it should allow the action and start a new empty chat instead

#### SCREENSHOT
![Screenshot (9)](https://user-images.githubusercontent.com/68507071/226912849-0fe3fa8f-b7c0-47ca-ac87-343ee3acd866.png)

**Comment by patrikzudel** [comment]
Good suggestion, fixed!
