### ISSUE TITLE
gpt-4 8k and 32k not available

### ISSUE THREAD

**Issue by parlortrickss** [patrikzudel/PatrikZeros-ChatGPT-API-UI#27]
- [X] I have read all open and **closed** Issues and confirm that this is not a duplicate.

I just cloned the repo to test it out. the 3.5 turbo works great but when i changed to either gpt4 option it states that they are not available. I don't know if this is a feature waiting to happen, an issue with the client or backend, so i reported it.

The error the client gives is: The model: gpt-4 does not exist

The way i repeated this was to just goto the settings and change from gpt3.5 to gpt4 8k or 32k. Then i just create a new prompt and it gives the above error code in the web client

I can see issue #21 is where the feature to change model was added.

**Expected behavior**
The gpt4 model options would work

**Desktop**
 - OS: EndevourOS (arch linux base)
 - Browser chromium
 - Version 111.0.5563.146 (Official Build) Arch Linux (64-bit)
 - Docker: version 23.0.2, build 569dd73db1
![gpt-issue](https://user-images.githubusercontent.com/94331028/229650716-777ba50d-e2e1-47be-90e7-7bf435a25f73.png)

**Comment by patrikzudel** [comment]
This is not a bug, this occurs when you try to access GPT4 while not having the access rights. (You need an invitation to use GPT4)
