### ISSUE TITLE
Bug Report - Deleting all messages causes site malfunction and prevents reloading

### ISSUE THREAD

**Issue by Sisimshow** [patrikzudel/PatrikZeros-ChatGPT-API-UI#3]
To reproduce the issue, clear all chats including the default empty chat. This will cause the site to stop responding. Reloading the page will result in a blank display. The only way to recover the site's functionality is by deleting site data.

This issue is particularly concerning for new users who may attempt to clear their test conversations and accidentally encounter this problem.

**Comment by patrikzudel** [comment]
Fixed, thanks!
