### ISSUE TITLE
Better error messaging

### ISSUE THREAD

**Issue by ManveerBhullar** [patrikzudel/PatrikZeros-ChatGPT-API-UI#8]
Currently, the error message is more confused than me 

> There was an error. Maybe the API key is wrong? Or the servers could be down?

The error message should instead be specific, so users can understand what the problem is. It can be figured out by digging into the dev console, but might as well surface it. For example, if its the token issue, that chat is never going to recover until msgs are deleted, so the user should know.

**Comment by patrikzudel** [comment]
Thanks, fixed.
